apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
      - name: uptime-kuma
        image: louislam/uptime-kuma:2
        ports:
        - containerPort: 3001
        volumeMounts:
        - name: storage
          mountPath: /app/data
      volumes:
      - name: storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma-service
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: uptime-kuma
  ports:
    - port: 80
      targetPort: 3001
      nodePort: 30005 # Cổng để bạn truy cập từ ngoài
